### ISSUE TITLE
Terse Sentences. Overused.

### ISSUE THREAD

**Issue by darthtrevino** [ardor-education/ardor-education.github.io#15]
There's way too much text here. We need to cut this back to two punchy phrases:

either:
"Math. Made Simple."
or
"Less Grading. More Teaching"

Throwing all of these in together makes the website feel like we weren't sure which advertising direction to go, so we chose all of them.

If we want some detail text in addition to the top-level punch-lines, then it should be in a regular prose style, and the font weight should be much thinner.

![screen shot 2016-10-05 at 1 50 07 pm](https://cloud.githubusercontent.com/assets/113544/19131065/c4062efa-8b02-11e6-8d61-b4a453ec77b6.png)

**Comment by MatthewThornton** [comment]
This whole section will be removed.
